# Generated by Django 4.2.3 on 2023-08-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
